# Generated by Django 3.0 on 2024-05-25 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('AM', 'Amazon'), ('EH', 'Ehabgroup'), ('JU', 'Jumia'), ('2B', '2B')], max_length=50)),
                ('country', models.CharField(choices=[('EG', 'Egypt')], max_length=50)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ScrapedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('SW', 'Smart Watch')], max_length=50)),
                ('description', models.TextField()),
                ('brand', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('EGP', 'Egyptian Pound'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='EGP', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_url', models.URLField()),
                ('image_url', models.URLField()),
                ('image', models.ImageField(upload_to='')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Website')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
