# Generated by Django 3.0 on 2024-05-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseproduct',
            name='product_type',
            field=models.CharField(choices=[('SW', 'Smart Watch')], default='SW', max_length=50),
        ),
    ]
