# Generated by Django 3.0 on 2024-06-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedproduct',
            name='image_url',
            field=models.URLField(max_length=500),
        ),
    ]
