# Generated by Django 3.0 on 2024-06-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20240613_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedproducttranslation',
            name='product_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='website',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
