# Generated by Django 3.0 on 2024-06-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20240613_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedproduct',
            name='image_url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='scrapedproducttranslation',
            name='product_url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='website',
            name='url',
            field=models.URLField(max_length=1000),
        ),
    ]
